$vCenters = @()
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH Midrand Waterfall'; 
    'IP Address'  = '10.1.5.254'; 
    'Common Name' = 'EOH Midrand Waterfall'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Passw00rd'}) # 'EOH Midrand Waterfall' # 1
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH PE'; 
    'IP Address'  = '10.1.33.8'; 
    'Common Name' = 'EOH PE'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'P@ssw0rd'}) # 'EOH PE'                # 2
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH Pinmill'; 
    'IP Address'  = '10.1.144.27'; 
    'Common Name' = 'EOH Pinmill'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'con42esx05'}) # 'EOH Pinmill'           # 3
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'PTA R21'; 
    'IP Address'  = '10.1.172.11'; 
    'Common Name' = 'PTA R21'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Passw00rd'}) # 'PTA R21'               # 4
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'Autospec'; 
    'IP Address'  = '10.1.81.11'; 
    'Common Name' = 'Autospec'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Fro0ple.'}) # 'Autospec'              # 5
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH KZN'; 
    'IP Address'  = '10.2.9.2'; 
    'Common Name' = 'EOH KZN'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Passw00rd'}) # 'EOH KZN'               # 6
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'KZN Grideye';
    'IP Address'  = '10.2.17.11'; 
    'Common Name' = 'KZN Gridey'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Fro0ple.'}) # 'KZN Gridey'            # 7
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH BT Cape Town'; 
    'IP Address'  = '10.3.0.11'; 
    'Common Name' = 'EOH BT Cape Town'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'password'}) # 'EOH BT Cape Town'      # 8
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH Cape Town'; 
    'IP Address'  = '10.3.0.12'; 
    'Common Name' = 'EOH Cape Town'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'password'}) # 'EOH Cape Town'         # 9
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'More SBT'; 
    'IP Address'  = '10.3.4.15';
    'Common Name' = 'More SBT'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Passw00rd'}) # 'More SBT'              # 10
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH-CLEARCPT-VHS1'; 
    'IP Address'  = '10.3.17.15'; 
    'Common Name' = 'EOH-CLEARCPT-VHS1'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Fro0ple'}) # 'EOH-CLEARCPT-VHS1'     # 11
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'Gilloolys'; 
    'IP Address'  = '10.10.4.100'; 
    'Common Name' = 'Gilloolys'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'EOHRT'; 
    'Password'    = '30HP@ssw0rd'}) # 'Gilloolys'             # 12
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH FIN'; 
    'IP Address'  = '10.10.6.16'; 
    'Common Name' = 'EOH FIN'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Passw00rd'}) # 'EOH FIN'               # 13
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'Amethyst'; 
    'IP Address'  = '10.10.180.35'; 
    'Common Name' = 'Amethyst'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'EOHRT@vsphere.local'; 
    'Password'    = '30HP@ssw0rd'}) # 'Amethyst'              # 14
$vCenters += ,(New-Object -TypeName PSObject -Property @{
    'System Name' = 'IMSSD';
    'IP Address'  = '10.12.255.110';
    'Common Name' = 'IMSSD';
    'Platform'    = 'VMWARE'; # Valid Options are HyperVCluster, HyperVStandalone, VMWare, Dummy
    'Username'    = 'EOHRT@vsphere.local';
    'Password'    = '30HP@ssw0rd';}) # 'IMSSD'                 # 15
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH Mitel Teraco'; 
    'IP Address'  = '10.12.255.201'; 
    'Common Name' = 'EOH Mitel Teraco'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Fro0ople.'}) # 'EOH Mitel Teraco'      # 16
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    'System Name' = 'EOH Mitel Bedfordview'; 
    'IP Address'  = '10.10.4.202'  ; 
    'Common Name' = 'EOH Mitel Bedfordview'; 
    'Platform'    = 'VMWare'; 
    'Username'    = 'root'; 
    'Password'    = 'Fro0ople.'}) # 'EOH Mitel Bedfordview' # 17
Clear-Host
For ($i = 0; $i -lt $vCenters.Count; $i ++) {
    $CommonName = ('(' + ($i + 1).ToString() + '-' + $vCenters.Count.ToString() + ') ' + $vCenters[$i].'Common Name')
    Write-Host (($i + 1).ToString() + "/" + $vCenters.Count.ToString() + " Processing Report for " + $vCenters[$i].'Common Name' + " - ") -NoNewLine
    C:\EOH_RT\Scripts\RT-Full-Module_v3.ps1 -SystemName $vCenters[$i].'System Name' -IPAddress $vCenters[$i].'IP Address' -CommonName $CommonName -Platform $vCenters[$i].'Platform' -Username $vCenters[$i].'Username' -Password $vCenters[$i].'Password'
    Write-Host "Complete"
}