# Copyright (c) Microsoft Corporation. All rights reserved.

# Autogenerated code, do not edit.

function Import-ScenarioSchema {
    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "PSImportedBy" -Value "0.0.4" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "DisplayName" -Value "AppControl" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "Description" -Value "Application Control for Business allows organizations to control which drivers and applications are allowed to run on their Windows clients." -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "Context" -Value "device"-Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "GetScenarioAlias" -Value "msftinventory" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "SetScenarioAlias" -Value "msftpolicies" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "AllSettingsRequired" -Value "false" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "Size" -Value 2 -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "Setting2" -Value "__PolicyIds" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "Order" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "DataType" -Value 9 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "CspName" -Value "./Vendor/MSFT/ApplicationControl" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "GetUriPath" -Value "Policies" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "UriPath" -Value "Policies/@#PolicyId#" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\__PolicyIds" -Name "Description" -Value "Array of Policy IDs" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\OperationalData" -Name "Setting1" -Value "Policies" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "Order" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "DataType" -Value 17 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "ObjectId" -Value "PolicyId" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "ObjectType" -Value "Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "CspName" -Value "./Vendor/MSFT/ApplicationControl" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "GetUriPath" -Value "Policies/@#PolicyId#" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "UriPath" -Value "Policies/@#PolicyId#" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "Description" -Value "List of policies for Application Control for Business and their details" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Settings\Policies" -Name "Transformer" -Value "Policy" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "AllSettingsRequired" -Value "false" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Size" -Value 11 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting1" -Value "Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting2" -Value "BasePolicyId" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting3" -Value "FriendlyName" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting4" -Value "IsAuthorized" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting5" -Value "IsBasePolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting6" -Value "IsDeployed" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting7" -Value "IsEffective" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting8" -Value "IsSystemPolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting9" -Value "Status" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting10" -Value "Version" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\OperationalData" -Name "Setting11" -Value "PolicyOptions" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Name "DataType" -Value 4 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Name "CspName" -Value "./Vendor/MSFT/ApplicationControl" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Name "GetUriPath" -Value "Policies/@#PolicyId#/Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Name "UriPath" -Value "Policies/@#PolicyId#/Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Policy" -Name "Order" -Value "1" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\BasePolicyId" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\BasePolicyId" -Name "DataType" -Value 3 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\BasePolicyId" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\BasePolicyId" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/BasePolicyId" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\BasePolicyId" -Name "RelativeUriPath" -Value "PolicyInfo/BasePolicyId" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\BasePolicyId" -Name "Order" -Value "2" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\FriendlyName" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\FriendlyName" -Name "DataType" -Value 3 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\FriendlyName" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\FriendlyName" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/FriendlyName" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\FriendlyName" -Name "RelativeUriPath" -Value "PolicyInfo/FriendlyName" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\FriendlyName" -Name "Order" -Value "3" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsAuthorized" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsAuthorized" -Name "DataType" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsAuthorized" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsAuthorized" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/IsAuthorized" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsAuthorized" -Name "RelativeUriPath" -Value "PolicyInfo/IsAuthorized" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsAuthorized" -Name "Order" -Value "4" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsBasePolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsBasePolicy" -Name "DataType" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsBasePolicy" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsBasePolicy" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/IsBasePolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsBasePolicy" -Name "RelativeUriPath" -Value "PolicyInfo/IsBasePolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsBasePolicy" -Name "Order" -Value "5" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsDeployed" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsDeployed" -Name "DataType" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsDeployed" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsDeployed" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/IsDeployed" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsDeployed" -Name "RelativeUriPath" -Value "PolicyInfo/IsDeployed" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsDeployed" -Name "Order" -Value "6" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsEffective" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsEffective" -Name "DataType" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsEffective" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsEffective" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/IsEffective" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsEffective" -Name "RelativeUriPath" -Value "PolicyInfo/IsEffective" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsEffective" -Name "Order" -Value "7" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsSystemPolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsSystemPolicy" -Name "DataType" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsSystemPolicy" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsSystemPolicy" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/IsSystemPolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsSystemPolicy" -Name "RelativeUriPath" -Value "PolicyInfo/IsSystemPolicy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\IsSystemPolicy" -Name "Order" -Value "8" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Status" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Status" -Name "DataType" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Status" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Status" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/Status" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Status" -Name "RelativeUriPath" -Value "PolicyInfo/Status" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Status" -Name "Order" -Value "9" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Version" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Version" -Name "DataType" -Value 3 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Version" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Version" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/Version" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Version" -Name "RelativeUriPath" -Value "PolicyInfo/Version" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\Version" -Name "Order" -Value "10" -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\PolicyOptions" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\PolicyOptions" -Name "DataType" -Value 3 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\PolicyOptions" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\PolicyOptions" -Name "GetUriPath" -Value "Policies/@#PolicyId#/PolicyInfo/PolicyOptions" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\PolicyOptions" -Name "RelativeUriPath" -Value "PolicyInfo/PolicyOptions" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\ApplicationControl\1.0.0\Objects\Policy\Settings\PolicyOptions" -Name "Order" -Value "11" -Force | Out-Null
}

# SIG # Begin signature block
# MIInwgYJKoZIhvcNAQcCoIInszCCJ68CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCw1frAfmm6AH5T
# 9biCy43VLCwFa+aRgKNQv72NpOXcWaCCDXYwggX0MIID3KADAgECAhMzAAADrzBA
# DkyjTQVBAAAAAAOvMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwOTAwWhcNMjQxMTE0MTkwOTAwWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDOS8s1ra6f0YGtg0OhEaQa/t3Q+q1MEHhWJhqQVuO5amYXQpy8MDPNoJYk+FWA
# hePP5LxwcSge5aen+f5Q6WNPd6EDxGzotvVpNi5ve0H97S3F7C/axDfKxyNh21MG
# 0W8Sb0vxi/vorcLHOL9i+t2D6yvvDzLlEefUCbQV/zGCBjXGlYJcUj6RAzXyeNAN
# xSpKXAGd7Fh+ocGHPPphcD9LQTOJgG7Y7aYztHqBLJiQQ4eAgZNU4ac6+8LnEGAL
# go1ydC5BJEuJQjYKbNTy959HrKSu7LO3Ws0w8jw6pYdC1IMpdTkk2puTgY2PDNzB
# tLM4evG7FYer3WX+8t1UMYNTAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQURxxxNPIEPGSO8kqz+bgCAQWGXsEw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMTgyNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAISxFt/zR2frTFPB45Yd
# mhZpB2nNJoOoi+qlgcTlnO4QwlYN1w/vYwbDy/oFJolD5r6FMJd0RGcgEM8q9TgQ
# 2OC7gQEmhweVJ7yuKJlQBH7P7Pg5RiqgV3cSonJ+OM4kFHbP3gPLiyzssSQdRuPY
# 1mIWoGg9i7Y4ZC8ST7WhpSyc0pns2XsUe1XsIjaUcGu7zd7gg97eCUiLRdVklPmp
# XobH9CEAWakRUGNICYN2AgjhRTC4j3KJfqMkU04R6Toyh4/Toswm1uoDcGr5laYn
# TfcX3u5WnJqJLhuPe8Uj9kGAOcyo0O1mNwDa+LhFEzB6CB32+wfJMumfr6degvLT
# e8x55urQLeTjimBQgS49BSUkhFN7ois3cZyNpnrMca5AZaC7pLI72vuqSsSlLalG
# OcZmPHZGYJqZ0BacN274OZ80Q8B11iNokns9Od348bMb5Z4fihxaBWebl8kWEi2O
# PvQImOAeq3nt7UWJBzJYLAGEpfasaA3ZQgIcEXdD+uwo6ymMzDY6UamFOfYqYWXk
# ntxDGu7ngD2ugKUuccYKJJRiiz+LAUcj90BVcSHRLQop9N8zoALr/1sJuwPrVAtx
# HNEgSW+AKBqIxYWM4Ev32l6agSUAezLMbq5f3d8x9qzT031jMDT+sUAoCw0M5wVt
# CUQcqINPuYjbS1WgJyZIiEkBMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGaIwghmeAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAOvMEAOTKNNBUEAAAAAA68wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEICv5uw9fdgmGgHKREtR9nVEv
# b3xhj/eF9AF293QuPJ/9MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAiUL0feFunV8RuPy3uk4rtTe6pGc6qCRp1ysmC7COUPVa5JYMyWdrdsWS
# sMjDbA/Ubav6VKTnKajqIge3XTlB8C0iclcxRcuXXk7C9qXyhlGmdQCIErREouZ5
# mDTyOebg5tMVDo+9KJXCA+ZktW3F1ZtHPk6GxUgy7qkMTYLHSiDhAd4fyJmit/6W
# VhddM6QDWOZLlNoEvP4BhjAkW+V/+wrZU1sdDLcnMqWc3oF7YOrqbJFuopg1HRvw
# bB7ydnHwbPjYtBooZHDp9h4c4KhorjXqHynrAnbh5vYuaukBSBpu7EumPJNQz1gc
# mQbHvjQTz9XG+aPmuwXhdmwZ67S4x6GCFywwghcoBgorBgEEAYI3AwMBMYIXGDCC
# FxQGCSqGSIb3DQEHAqCCFwUwghcBAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCDLn44WnGCVqzY5pdh6Uej1F0U3geTCtBbLpp7Ob+aiCAIGZdZEGeuo
# GBMyMDI0MDMxMjE5MDE1OS4yMTRaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# OkQwODItNEJGRC1FRUJBMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIRezCCBycwggUPoAMCAQICEzMAAAHcweCMwl9YXo4AAQAAAdwwDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjMx
# MDEyMTkwNzA2WhcNMjUwMTEwMTkwNzA2WjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpEMDgyLTRC
# RkQtRUVCQTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAIvIsyA1sjg9kSKJzelrUWF5
# ShqYWL83amn3SE5JyIVPUC7F6qTcLphhHZ9idf21f0RaGrU8EHydF8NxPMR2KVNi
# AtCGPJa8kV1CGvn3beGB2m2ltmqJanG71mAywrkKATYniwKLPQLJ00EkXw5TSwfm
# JXbdgQLFlHyfA5Kg+pUsJXzqumkIvEr0DXPvptAGqkdFLKwo4BTlEgnvzeTfXukz
# X8vQtTALfVJuTUgRU7zoP/RFWt3WagahZ6UloI0FC8XlBQDVDX5JeMEsx7jgJDdE
# nK44Y8gHuEWRDq+SG9Xo0GIOjiuTWD5uv3vlEmIAyR/7rSFvcLnwAqMdqcy/iqQP
# MlDOcd0AbniP8ia1BQEUnfZT3UxyK9rLB/SRiKPyHDlg8oWwXyiv3+bGB6dmdM61
# ur6nUtfDf51lPcKhK4Vo83pOE1/niWlVnEHQV9NJ5/DbUSqW2RqTUa2O2KuvsyRG
# MEgjGJA12/SqrRqlvE2fiN5ZmZVtqSPWaIasx7a0GB+fdTw+geRn6Mo2S6+/bZEw
# S/0IJ5gcKGinNbfyQ1xrvWXPtXzKOfjkh75iRuXourGVPRqkmz5UYz+R5ybMJWj+
# mfcGqz2hXV8iZnCZDBrrnZivnErCMh5Flfg8496pT0phjUTH2GChHIvE4SDSk2hw
# WP/uHB9gEs8p/9Pe/mt9AgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQU6HPSBd0OfEX3
# uNWsdkSraUGe3dswHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBANnrb8Ewr8eX/H1s
# Kt3rnwTDx4AqgHbkMNQo+kUGwCINXS3y1GUcdqsK/R1g6Tf7tNx1q0NpKk1JTupU
# JfHdExKtkuhHA+82lT7yISp/Y74dqJ03RCT4Q+8ooQXTMzxiewfErVLt8Wefebnc
# ST0i6ypKv87pCYkxM24bbqbM/V+M5VBppCUs7R+cETiz/zEA1AbZL/viXtHmryA0
# CGd+Pt9c+adsYfm7qe5UMnS0f/YJmEEMkEqGXCzyLK+dh+UsFi0d4lkdcE+Zq5JN
# jIHesX1wztGVAtvX0DYDZdN2WZ1kk+hOMblUV/L8n1YWzhP/5XQnYl03AfXErn+1
# Eatylifzd3ChJ1xuGG76YbWgiRXnDvCiwDqvUJevVRY1qy4y4vlVKaShtbdfgPyG
# eeJ/YcSBONOc0DNTWbjMbL50qeIEC0lHSpL2rRYNVu3hsHzG8n5u5CQajPwx9Pzp
# sZIeFTNHyVF6kujI4Vo9NvO/zF8Ot44IMj4M7UX9Za4QwGf5B71x57OjaX53gxT4
# vzoHvEBXF9qCmHRgXBLbRomJfDn60alzv7dpCVQIuQ062nyIZKnsXxzuKFb0TjXW
# w6OFpG1bsjXpOo5DMHkysribxHor4Yz5dZjVyHANyKo0bSrAlVeihcaG5F74SZT8
# FtyHAW6IgLc5w/3D+R1obDhKZ21WMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtcwggJAAgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpE
# MDgyLTRCRkQtRUVCQTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUAHDn/cz+3yRkIUCJfSbL3djnQEqaggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOmbHzIwIhgPMjAyNDAzMTMwMjM2MzRaGA8yMDI0MDMxNDAyMzYzNFowdzA9Bgor
# BgEEAYRZCgQBMS8wLTAKAgUA6ZsfMgIBADAKAgEAAgICGQIB/zAHAgEAAgIS8jAK
# AgUA6ZxwsgIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIB
# AAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBAIYeAFbpQYQhJ2uS
# 8Il99tnIZcWWfXYEoaPe8J69VHUWEs3ETUtjZKg/FMvUsPZkIsNEp5oViNUi601a
# 0lJiyB4dQaMuGitdri53arj7WtTVPIt9nyfD9K6uYjh6fmcwBhbD0P9hrw5HF8Yl
# 362sGAeXCgERwyLmra1HIaPmvJMJMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTACEzMAAAHcweCMwl9YXo4AAQAAAdwwDQYJYIZIAWUD
# BAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0B
# CQQxIgQgwnbGrfD+JGGwYUbn8duC3b1omfjMVHwch96RZGhsCaAwgfoGCyqGSIb3
# DQEJEAIvMYHqMIHnMIHkMIG9BCBTpxeKatlEP4y8qZzjuWL0Ou0IqxELDhX2TLyl
# xIINNzCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
# 3MHgjMJfWF6OAAEAAAHcMCIEICwp8oFBUZRHOU4/QxLNTIKLeEEL60BXYBiepw5S
# lZRhMA0GCSqGSIb3DQEBCwUABIICACqtaKJCAxC46ejTD2JEQVr51+UImzUz5eN2
# fN2b8jIIHEb/BwcG3PBpGXctoJyrp4izkcWk9RKX3gA0Bvqc2egT1dvauo5Zt6fA
# z28MafakcGyblzvu8mznBW19W2JC8DOhS1tY0x3z8eisjEoU/C2nTDbvqu2RKLd2
# 7cewydJ42neEOD0aX87UxiwtqwrfDCFps+4PNUN8Ym2N7BkjZg75MalXIS7WYp/3
# ijl0o1KWYfb0sO2uE8OZwGU1jwnN2sAXEIEQaPqMoERIL84FetzgmUZt5NFnPBaf
# FobEAspDJNjE4bDOzW8vXxMEPYfdqiZu03oeR7LV1UrN8O34DST5/PYLRx+aubI5
# mdU2f0FXMoO4PjK2SB/26yeFYYo4T3mbyqOnxIGBARLAk6T/bxWeoPfvAfyhLTqC
# xfubZODxwprkUShn8gpMizZhyS266VOa6sTzgGMOECNZdJdwxwPqJu4pBluumYbi
# 5gr6S5msDMf7BzHhVxcnrTdj5CwN18lC1NTvj7V/skLd4M8HDSb2nIjaHemXbtFr
# Dn9fvJsWyhJF9IXxTsZGsKbN5fDpothp7c3kD2nHurpe8JhOmNxsHf9LBmN4rFwV
# PU3NzkSJzEa7oj3xmIAqFEFFzwZqu/fY/kYR3oqwB0wth0tGUlyjp+q0EMu/GXuk
# E+Ae0PCA
# SIG # End signature block
