Clear-Host
$ErrorActionPreference = "Stop"
$Servers = @(
    "ANDILESAS"
    "ANGIEPOSOFFLINE"
    "ANGIEPOSONLINE"
    "CAROLINESHAREP"
    "DEBBYSVR2012"
    "DEVSERVERRC7"
    "DFRYERSQLBOX"
    "ERRTRKSERVER"
    "GOODFELLOWS"
    "INFOZONEDEVNEW"
    "KCCPROJECT"
    "LEATITIA-SERVER"
    "LEATITIASVR"
    "POS7MAINC"
    "POS7MAINSVR"
    "SASPOSTEST"
    "SASTESTNEW"
    "SERVER2012R2TS"
    "SERVER2016"
    "SHAREPOINTTEMP1"
    "SHAREPOINTTEMP2"
    "SS-SHANESVRSIDE"
    "SYSCTDC"
    "SYSDBNDC"
    "SYSJHBACC"
    "SYSJHBAVE"
    "SYSJHBCLUSTER"
    "SYSJHBCRM"
    "SYSJHBDC"
    "SYSJHBDEV"
    "SYSJHBDEVAUTO"
    "SYSJHBDPM"
    "SYSJHBDS2012R2"
    "SYSJHBDW"
    "SYSJHBERRTRK"
    "SYSJHBFS"
    "SYSJHBFTP"
    "SYSJHBHV1"
    "SYSJHBHV2"
    "SYSJHBHV3"
    "SYSJHBHV4"
    "SYSJHBHVTR"
    "SYSJHBHVTR2"
    "SYSJHBHVTR3"
    "SYSJHBLYNC"
    "SYSJHBLYNCAPP"
    "SYSJHBLYNCPICKU"
    "SYSJHBMAIL"
    "SYSJHBMFP"
    "SYSJHBOPSMGR"
    "SYSJHBOWA"
    "SYSJHBPRINT"
    "SYSJHBPROFSERV"
    "SYSJHBPROPHIX"
    "SYSJHBPROXY"
    "SYSJHBSERVMAN"
    "SYSJHBSMAN-DW"
    "SYSJHBSMPORTAL"
    "SYSJHBSP"
    "SYSJHBSP16DEV"
    "SYSJHBSP2"
    "SYSJHBSPDEV"
    "SYSJHBSPDZ"
    "SYSJHBSPUAT"
    "SYSJHBSQLSP"
    "SYSJHBSQLSS"
    "SYSJHBSSS"
    "SYSJHBSTORE"
    "SYSJHBSYSCENTRE"
    "SYSJHBTESTDEV"
    "SYSJHBTESTHV"
    "SYSJHBTESTHV2"
    "SYSJHBTFSDEV"
    "SYSJHBVIP"
    "SYSJHBVMM"
    "SYSJHBWA"
    "SYSJHBWEBDEVDB"
    "SYSJHBWEBGEN"
    "SYSPRO7SVR12"
    "SYSPROCMS"
    "SYSPRO-DCVM"
    "SYSPROWIN2012"
    "SYS-SS-POS6S"
    "SYS-SS-POS7S"
    "SYS-SS-POSSRV"
    "SYSTEMTEST"
    "THABOT"
    "VM2013SERVER"
    "VM-SHANETESTING"
    "VM-STHESP2013"
    "VM-SYSTEMSQL"
    "VUSIWIN12")

ForEach ($Server in $Servers) {
    Write-Host "Collecting Installed Products on $Server - " -NoNewline
    Try {
        Test-Connection $Server -Count 1 | Out-Null
        $Roles = Get-WindowsFeature -ComputerName $Server | Where InstallState -eq Installed
        $Roles | Out-File -FilePath c:\temp\$Server-Roles.txt -Encoding ascii -Force -NoClobber
        Write-Host "Complete" -ForegroundColor Green
    }
    Catch [System.Net.WebException],[System.Exception] {
        Write-Host "Failed" -ForegroundColor Red
    }
}