$vCenters = @()
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Midrand Waterfall';
    IPAddress  = '10.1.5.254';
    CommonName = 'EOH Midrand Waterfall';
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Passw00rd';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH PE'; 
    IPAddress  = '10.1.33.8'; 
    CommonName = 'EOH PE'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'P@ssw0rd';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH ERS'; 
    IPAddress  = '10.1.130.5'   ; 
    CommonName = 'EOH ERS'              ;
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'EohAbacus!';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Pinmill'; 
    IPAddress  = '10.1.144.27'; 
    CommonName = 'EOH Pinmill'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'con42esx05';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH PTA R21'; 
    IPAddress  = '10.1.172.11'; 
    CommonName = 'PTA R21'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Passw00rd';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Autospec'; 
    IPAddress  = '10.1.238.11'; 
    CommonName = 'Autospec'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Fro0ple.';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH KZN'; 
    IPAddress  = '10.2.9.2'; 
    CommonName = 'EOH KZN'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Passw00rd';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH KZN Grideye'; 
    IPAddress  = '10.2.17.11'; 
    CommonName = 'KZN Grideye'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Fro0ple.';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Armstrong'; 
    IPAddress  = '10.2.20.11'; 
    CommonName = 'Armstrong'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Fro0ple';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH SBT Cape Town'; 
    IPAddress  = '10.3.0.11'; 
    CommonName = 'EOH SBT Cape Town'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'password';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Cape Town'; 
    IPAddress  = '10.3.0.12'; 
    CommonName = 'EOH Cape Town'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'password';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH More SBT'; 
    IPAddress  = '10.3.4.15'; 
    CommonName = 'More SBT'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Passw00rd';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH-CLEARCPT-VHS1'; 
    IPAddress  = '10.3.17.11'; 
    CommonName = 'EOH-CLEARCPT-VHS1'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Fro0ple';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Gilloolys'; 
    IPAddress  = '10.10.4.100'; 
    CommonName = 'Gilloolys'; 
    Platform   = 'VMWare';
    Username   = 'eohcorp\aims';
    Password   = 'Sj-9Mu.4Ae-8';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH FIN'; 
    IPAddress  = '10.10.6.16'; 
    CommonName = 'EOH FIN'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'Passw00rd';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Amethyst'; 
    IPAddress  = '10.10.180.35'; 
    CommonName = 'Amethyst'; 
    Platform   = 'VMWare';
    Username   = 'eohcorp\aims';
    Password   = 'Sj-9Mu.4Ae-8';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH Teraco'; 
    IPAddress  = '10.12.5.230'; 
    CommonName = 'Teraco'; 
    Platform   = 'VMWare';
    Username   = 'root';
    Password   = 'P@ssw0rd1';})
$vCenters += ,(New-Object -TypeName PSObject -Property @{ 
    SystemName = 'EOH IMSSD'; 
    IPAddress  = '10.12.255.110'; 
    CommonName = 'IMSSD'; 
    Platform   = 'VMWare';
    Username   = 'eohcorp\aims';
    Password   = 'Sj-9Mu.4Ae-8';})

For ($i = 0; $i -lt $vCenters.Count; $i ++) {
    Write-Host (($i + 1).ToString() + "/" + $vCenters.Count.ToString() + " Processing Report for " + $vCenters[$i].CommonName + " - ") -NoNewLine
    $PasswordFile = ('C:\EOH_RT\Scripts\Config-' + $vCenters[$i].CommonName + '-Config.PSF')
    C:\EOH_RT\Scripts\RT-Full-Module.ps1 -SystemName $vCenters[$i].SystemName -IPAddress $vCenters[$i].IPAddress -CommonName $vCenters[$i].CommonName -Platform $vCenters[$i].Platform -Username $vCenters[$i].Username -Password $vCenters[$i].Password
    Write-Host "Complete"
}