$Customers = @()
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '702563'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '710550'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '765688'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '809450'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '823638'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '904708'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '942034'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '943975'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '943980'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '947354'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '964767'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '988717'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1002698'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1012699'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1101920'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1117579'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1151575'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1189054'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1228522'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1238270'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1243684'; Name = 'EOH'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1318778'; Name = 'EOH'})

.\LiveVault-Report-Multi-XLSX.ps1 -CustomerIDs $Customers.ID -CustomerName $Customers[0].Name

$Customers = @()
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '749183'; Name = 'ERWAT'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '760304'; Name = 'Vunene Mining'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '793523'; Name = 'SekelaXabiso'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '873176'; Name = 'Homemark'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '897417'; Name = 'Broll'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '941674'; Name = 'African Group Lubricants'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '951340'; Name = 'Eskort Ltd'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1035261'; Name = 'PG Group'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1086932'; Name = 'Calgro M3'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1094936'; Name = 'KAP Bedding'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1127279'; Name = 'GOLDPLAT'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1128532'; Name = 'Life Health Care'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1182767'; Name = 'BBF Safety Group'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1183404'; Name = 'RandGold Resources Limited'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1185811'; Name = 'Ocean Basket'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1188752'; Name = 'NEMISA'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1197050'; Name = 'National Skills Fund'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1202825'; Name = 'Knox Titanium Vault Company'})
$Customers += ,(New-Object -TypeName PSObject -Property @{ID = '1318967'; Name = 'Isanti Glass'})

For ($i = 0; $i -lt $Customers.Count; $i ++) {
    Write-Color -IndexCounter $i -TotalCounter $Customers.Count -Text 'Processing ', $Customers[$i].Name, ' - ' -ForegroundColor Green, Yellow, Green
    .\LiveVault-Report-Multi-XLSX.ps1 -CustomerIDs $Customers[$i].ID -CustomerName $Customers[$i].Name
}