# Copyright (c) Microsoft Corporation. All rights reserved.

# Autogenerated code, do not edit.

function Import-ScenarioSchema {
    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "PSImportedBy" -Value "0.0.4" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "Description" -Value "Secured-core is a collection of capabilities that offers built-in hardware, firmware, driver and operating system security features." -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "Context" -Value "device"-Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "GetScenarioAlias" -Value "msftinventory" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "SetScenarioAlias" -Value "msftpolicies" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "AllSettingsRequired" -Value "false" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "Size" -Value 3 -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "Setting3" -Value "ConfigureSystemGuardLaunch" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "Order" -Value 3 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "DataType" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "CspName" -Value "./Vendor/MSFT/Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "GetUriPath" -Value "Result/DeviceGuard/ConfigureSystemGuardLaunch" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "UriPath" -Value "Config/DeviceGuard/ConfigureSystemGuardLaunch" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "Description" -Value "Using processor support for Dynamic Root of Trust of Measurement (DRTM) technology, System Guard puts firmware in a hardware-based sandbox helping to limit the impact of vulnerabilities in millions of lines of highly privileged firmware code." -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "MinValue" -Value 0 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "MaxValue" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\ConfigureSystemGuardLaunch" -Name "DefaultValue" -Value 1 -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "Setting1" -Value "EnableVirtualizationBasedSecurity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "Order" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "DataType" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "CspName" -Value "./Vendor/MSFT/Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "GetUriPath" -Value "Result/DeviceGuard/EnableVirtualizationBasedSecurity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "UriPath" -Value "Config/DeviceGuard/EnableVirtualizationBasedSecurity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "Description" -Value "Virtualization-based security, or VBS, uses hardware virtualization features to create and isolate a secure region of memory from the normal operating system. This helps to ensure that servers remain devoted to running critical workloads and helps protect related applications and data from attack and exfiltration." -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "MinValue" -Value 0 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "MaxValue" -Value 1 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\EnableVirtualizationBasedSecurity" -Name "DefaultValue" -Value 1 -Force | Out-Null

    New-Item -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\OperationalData" -Name "Setting2" -Value "HypervisorEnforcedCodeIntegrity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "Order" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "DataType" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "Provider" -Value "csp" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "CspName" -Value "./Vendor/MSFT/Policy" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "GetUriPath" -Value "Result/VirtualizationBasedTechnology/HypervisorEnforcedCodeIntegrity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "UriPath" -Value "Config/VirtualizationBasedTechnology/HypervisorEnforcedCodeIntegrity" -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "Description" -Value "Memory integrity, also known as Hypervisor-protected Code Integrity (HVCI), uses an isolated virtual environment to run integrity checks of kernel mode software, enhancing protection against malware trying to exploit the OS kernel." -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "MinValue" -Value 0 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "MaxValue" -Value 2 -Force | Out-Null
    Set-ItemProperty -Path "$($Script:Constants.RegistryKeyPath.ScenarioSchema)\1.0\SecuredCore\1.0\Settings\HypervisorEnforcedCodeIntegrity" -Name "DefaultValue" -Value 2 -Force | Out-Null
}

# SIG # Begin signature block
# MIInwgYJKoZIhvcNAQcCoIInszCCJ68CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAiE9iUPogAAkZ5
# GcQW6ujk9uOC59t34EfBlHqVd9lx+6CCDXYwggX0MIID3KADAgECAhMzAAADrzBA
# DkyjTQVBAAAAAAOvMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwOTAwWhcNMjQxMTE0MTkwOTAwWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDOS8s1ra6f0YGtg0OhEaQa/t3Q+q1MEHhWJhqQVuO5amYXQpy8MDPNoJYk+FWA
# hePP5LxwcSge5aen+f5Q6WNPd6EDxGzotvVpNi5ve0H97S3F7C/axDfKxyNh21MG
# 0W8Sb0vxi/vorcLHOL9i+t2D6yvvDzLlEefUCbQV/zGCBjXGlYJcUj6RAzXyeNAN
# xSpKXAGd7Fh+ocGHPPphcD9LQTOJgG7Y7aYztHqBLJiQQ4eAgZNU4ac6+8LnEGAL
# go1ydC5BJEuJQjYKbNTy959HrKSu7LO3Ws0w8jw6pYdC1IMpdTkk2puTgY2PDNzB
# tLM4evG7FYer3WX+8t1UMYNTAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQURxxxNPIEPGSO8kqz+bgCAQWGXsEw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMTgyNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAISxFt/zR2frTFPB45Yd
# mhZpB2nNJoOoi+qlgcTlnO4QwlYN1w/vYwbDy/oFJolD5r6FMJd0RGcgEM8q9TgQ
# 2OC7gQEmhweVJ7yuKJlQBH7P7Pg5RiqgV3cSonJ+OM4kFHbP3gPLiyzssSQdRuPY
# 1mIWoGg9i7Y4ZC8ST7WhpSyc0pns2XsUe1XsIjaUcGu7zd7gg97eCUiLRdVklPmp
# XobH9CEAWakRUGNICYN2AgjhRTC4j3KJfqMkU04R6Toyh4/Toswm1uoDcGr5laYn
# TfcX3u5WnJqJLhuPe8Uj9kGAOcyo0O1mNwDa+LhFEzB6CB32+wfJMumfr6degvLT
# e8x55urQLeTjimBQgS49BSUkhFN7ois3cZyNpnrMca5AZaC7pLI72vuqSsSlLalG
# OcZmPHZGYJqZ0BacN274OZ80Q8B11iNokns9Od348bMb5Z4fihxaBWebl8kWEi2O
# PvQImOAeq3nt7UWJBzJYLAGEpfasaA3ZQgIcEXdD+uwo6ymMzDY6UamFOfYqYWXk
# ntxDGu7ngD2ugKUuccYKJJRiiz+LAUcj90BVcSHRLQop9N8zoALr/1sJuwPrVAtx
# HNEgSW+AKBqIxYWM4Ev32l6agSUAezLMbq5f3d8x9qzT031jMDT+sUAoCw0M5wVt
# CUQcqINPuYjbS1WgJyZIiEkBMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGaIwghmeAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAOvMEAOTKNNBUEAAAAAA68wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIEjkzccW8AgHJ1/IKgf+z0/v
# yYaz+z0S6sXijD7Dp6tWMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAYWZEUBCpK3ul9GHEujC7bTtxFQiOCp8unNeWI9AE+36fOiejkpF9LeMk
# N1VpIHes9LHqbbf1Fij1j7HB33RgBbOzfGWsCKmQxkr5KrVQ3aukdn31JgQ75iwc
# RE2uxxRV+sNDg5e+r6SpaN9kJo+7jJ+i8FA5USTv/GrJqeggTW58F+i2kO4gRtOV
# Q2fcBJXcL2qw3Lh8q6EBVutRosvjWnPGHpr+o7++sOlBRnuXzPw+la8OEHlRXK2E
# RaERjkNhKKSmqw4HnOH4JC3cmhzKblS9k3CcYExaFXhkkRjnzt/roXc0xYRjYKX3
# L8jY6PgbWy+yYaMNG5yGqsgK2tjOQKGCFywwghcoBgorBgEEAYI3AwMBMYIXGDCC
# FxQGCSqGSIb3DQEHAqCCFwUwghcBAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCD6CSBTxq1/jtRYZaaYjs1dixa5wISzUXhs1obkF1oeCgIGZdXh/gYX
# GBMyMDI0MDMxMjE5MDE1OS4yNTFaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# OjJBRDQtNEI5Mi1GQTAxMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIRezCCBycwggUPoAMCAQICEzMAAAHenkielp8oRD0AAQAAAd4wDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjMx
# MDEyMTkwNzEyWhcNMjUwMTEwMTkwNzEyWjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoyQUQ0LTRC
# OTItRkEwMTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALSB9ByF9UIDhA6xFrOniw/x
# sDl8sSi9rOCOXSSO4VMQjnNGAo5VHx0iijMEMH9LY2SUIBkVQS0Ml6kR+TagkUPb
# aEpwjhQ1mprhRgJT/jlSnic42VDAo0en4JI6xnXoAoWoKySY8/ROIKdpphgI7OJb
# 4XHk1P3sX2pNZ32LDY1ktchK1/hWyPlblaXAHRu0E3ynvwrS8/bcorANO6Djuysy
# S9zUmr+w3H3AEvSgs2ReuLj2pkBcfW1UPCFudLd7IPZ2RC4odQcEPnY12jypYPnS
# 6yZAs0pLpq0KRFUyB1x6x6OU73sudiHON16mE0l6LLT9OmGo0S94Bxg3N/3aE6fU
# bnVoemVc7FkFLum8KkZcbQ7cOHSAWGJxdCvo5OtUtRdSqf85FklCXIIkg4sm7nM9
# TktUVfO0kp6kx7mysgD0Qrxx6/5oaqnwOTWLNzK+BCi1G7nUD1pteuXvQp8fE1Kp
# TjnG/1OJeehwKNNPjGt98V0BmogZTe3SxBkOeOQyLA++5Hyg/L68pe+DrZoZPXJa
# GU/iBiFmL+ul/Oi3d83zLAHlHQmH/VGNBfRwP+ixvqhyk/EebwuXVJY+rTyfbRfu
# h9n0AaMhhNxxg6tGKyZS4EAEiDxrF9mAZEy8e8rf6dlKIX5d3aQLo9fDda1ZTOw+
# XAcAvj2/N3DLVGZlHnHlAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUazAmbxseaapg
# dxzK8Os+naPQEsgwHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAOKUwHsXDacGOvUI
# gs5HDgPs0LZ1qyHS6C6wfKlLaD36tZfbWt1x+GMiazSuy+GsxiVHzkhMW+FqK8gr
# uLQWN/sOCX+fGUgT9LT21cRIpcZj4/ZFIvwtkBcsCz1XEUsXYOSJUPitY7E8bbld
# mmhYZ29p+XQpIcsG/q+YjkqBW9mw0ru1MfxMTQs9MTDiD28gAVGrPA3NykiSChvd
# qS7VX+/LcEz9Ubzto/w28WA8HOCHqBTbDRHmiP7MIj+SQmI9VIayYsIGRjvelmNa
# 0OvbU9CJSz/NfMEgf2NHMZUYW8KqWEjIjPfHIKxWlNMYhuWfWRSHZCKyIANA0aJL
# 4soHQtzzZ2MnNfjYY851wHYjGgwUj/hlLRgQO5S30Zx78GqBKfylp25aOWJ/qPhC
# +DXM2gXajIXbl+jpGcVANwtFFujCJRdZbeH1R+Q41FjgBg4m3OTFDGot5DSuVkQg
# jku7pOVPtldE46QlDg/2WhPpTQxXH64sP1GfkAwUtt6rrZM/PCwRG6girYmnTRLL
# sicBhoYLh+EEFjVviXAGTk6pnu8jx/4WPWu0jsz7yFzg82/FMqCk9wK3LvyLAyDH
# N+FxbHAxtgwad7oLQPM0WGERdB1umPCIiYsSf/j79EqHdoNwQYROVm+ZX10RX3n6
# bRmAnskeNhi0wnVaeVogLMdGD+nqMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtcwggJAAgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoy
# QUQ0LTRCOTItRkEwMTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUAaKBSisy4y86pl8Xy22CJZExE2vOggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOmavagwIhgPMjAyNDAzMTIxOTQwMjRaGA8yMDI0MDMxMzE5NDAyNFowdzA9Bgor
# BgEEAYRZCgQBMS8wLTAKAgUA6Zq9qAIBADAKAgEAAgIFbQIB/zAHAgEAAgIRHTAK
# AgUA6ZwPKAIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIB
# AAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBABy+JodADJFIA9LQ
# cA4ZNdLvsl6We2PnGL0dcsmBkW5AwnCGa3dPGZqXnYCvoT3aAXRyaYIFEBhfJGdP
# 0p2TStpZRK4FDImUqwI7awSQVctIKJCDN5YH2yCtk84cZuXZIamMkBQiFIlgEZgh
# 5igzp/Xog16xspsrIHP1Mq90dE3dMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTACEzMAAAHenkielp8oRD0AAQAAAd4wDQYJYIZIAWUD
# BAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0B
# CQQxIgQgS/+xtN2E5nzis99yz/LVQyRXJd/dX5eIoG/6xu2edRAwgfoGCyqGSIb3
# DQEJEAIvMYHqMIHnMIHkMIG9BCCOPiOfDcFeEBBJAn/mC3MgrT5w/U2z81LYD44H
# c34dezCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
# 3p5InpafKEQ9AAEAAAHeMCIEIJwA4JfG5Q2PdU+7j4UrCWU8fSxjFU1Mox3wcvGY
# Y6kBMA0GCSqGSIb3DQEBCwUABIICAGNgXBcBG0FYWnByYGbpMNqpR+UBDNqB9JMs
# rXZphWmMof4iEqhhHjHSDbiTQHvHEHi3c727ukAcaD90mKC5BSjmtXFeUMHEEXYH
# 5Nu3G//e0MSaMlUHgcgpWmiTFO2v9WH3QD8eprdkqqfv35w8SMQAfROWTC1VKy0n
# nlNj0UlH5o/aWm9l6Ky8slfA3M+lW6dJ6XT1k0WLZJp1+7To3jOao69D+qLWoXMf
# oE+WBahmxYI4jqUUBWl9ZpKE5iDnLaD8DtROZ7qWqfZKtVGgdORyT4Emg0ezWVZX
# H8MdY5JOF4chXGlVZzHAIttkiB3dLsJNJpp36m7RGqw3gABMqhRxDe+LNJWs6qV3
# zWwYVqZLvQk1Qhc9KfmdSuogFXZm+JnpuEe/LetPlXbVS662meswOLN31GEIPho8
# QHkoDgG1zOZsiySEjagxJWhBU88KBzRvmUcxQtwmVVq8jE2bCPCMPN8GlMXM23pw
# OzZQKQ+32l9jVdZK1IjvAdLNdxdiAmEu1Lt5qXFz6KWuDQO7rWqqiO7zZNY3B/K3
# WVViGpUroRxnu/3Wkq6djnjq5rIsF3ZtMYjnHGIuEm7AeZ+8kVkDyrsnLYLH6IRD
# pkTdhj1G4kF2duydPL/R2BIhPMWvZVwO8lwMedcHBaovNxZQ68MnhOP7hHN7gN10
# sj4mOgp1
# SIG # End signature block
