$ErrorActionPreference = 'Stop'
$Servers = @()
$Servers += ,('CBWLPPRAPW219')
$Servers += ,('CBAWPPRAPL031')
$Servers += ,('CBWLPPRDBW215')
$Servers += ,('RPOBSERVAFPRD2')
$Servers += ,('CBDBPPRDBW019')
$Servers += ,('CBWLPPRWFW022')
$Servers += ,('CBWLPPRAPW524')
$Servers += ,('CBAWPPRAPW019')
$Servers += ,('CBKVPPRDBL008')
$Servers += ,('CBVMPPRAPW102')
$Servers += ,('CBAWPPRAPW016')
$Servers += ,('CBWLPPRWFW040')
$Servers += ,('CBWLPPRDBW225')
$Servers += ,('WPWSPENGLDCM01')
$Servers += ,('RPNETWRKNORD01')
$Servers += ,('CBWLPPRAPL398')
$Servers += ,('WPPENTSTCTR701')
$Servers += ,('CBWLPPRAPW146')
$Servers += ,('CBWLPPRAPW218')
$Servers += ,('CBAWPPRDBW030')
$Servers += ,('CBAWPPRAPL212')
$Servers += ,('WPCLDEDLBLOBS3')
$Servers += ,('WPPENTSTCTR702')
$Servers += ,('CBAWPPRAPW038')
$Servers += ,('WPTSCBRBSSWR03')
$Servers += ,('APDAAIENGDOCS')
$Servers += ,('CBWLPPRAPW407')
$Servers += ,('CBVMPPRAPL014')
$Servers += ,('CBAWPPRAPW037')
$Servers += ,('CBWLPPRAPW644')
$Servers += ,('CBAWPPRAPW039')
$Servers += ,('CBWLPPRAPW614')
$Servers += ,('CBWLPPRAPW229')
$Servers += ,('CBWLPPRWFW026')
$Servers += ,('CBVMPPRAPW097')
$Servers += ,('CBWLPPRDBW319')
$Servers += ,('CBVMPPRDBW012')
$Servers += ,('CBWLPPRDBL036')
$Servers += ,('CBVMPPRAPL015')
$Servers += ,('CBAWPPRAPW295')
$Servers += ,('CBWLPPRWFW027')
$Servers += ,('CBWLPPRDBL043')
$Servers += ,('cbdaonlnprd01')
$Servers += ,('CBAWPPRDBW027')
$Servers += ,('APBDCARDSHD01A')
$Servers += ,('RPWSPENGMTA01')
$Servers += ,('CBWLPPRWFW007')
$Servers += ,('amlrcmdb')
$Servers += ,('CBWLPPRDBL031')
$Servers += ,('RPISAENGDAPRD')
$Servers += ,('APISAENGNAGT11')
$Servers += ,('CBWLPPRWFW025')
$Servers += ,('CBDBPPRDBW007')
$Servers += ,('CBWLPPRDBW036')
$Servers += ,('WPTSCBRBDSAPP1')
$Servers += ,('CBWLPPRDBW309')
$Servers += ,('CBWLPPRAPL292')
$Servers += ,('CBWLPPRAPW336')
$Servers += ,('CBAWPPRAPW025')
$Servers += ,('CBAWPPRAPW277')
$Servers += ,('CBAWPPRAPW281')
$Servers += ,('CBVMPPRAPW024')
$Servers += ,('CBWLPPRWFW092')
$Servers += ,('CBAWPPRAPW278')
$Servers += ,('CBAWPPRAPW280')
$Servers += ,('CBWLPPRWFW089')
$Servers += ,('CBWLPPRWFW099')
$Servers += ,('APISAENGNETAG8')
$Servers += ,('CBWLPPRWFW094')
$Servers += ,('CBWLPPRWFW100')
$Servers += ,('CBWLPPRDBW240')
$Servers += ,('cbzanaps02')
$Servers += ,('APDAAIENGGAEFB')
$Servers += ,('WPPAYHCPWPWF01')
$Servers += ,('CBAWPPRAPL182')
$Servers += ,('CBVMPPRDBW009')
$Servers += ,('CBWLPPRWFW093')
$Servers += ,('CBWLPPRDBW201')
$Servers += ,('WPPAYHCPWPWF02')
$Servers += ,('CBWLPPRWFW090')
$Servers += ,('CBWLPPRAPW233')
$Servers += ,('WPPAYHCPWPTX01')
$Servers += ,('CBWLPPRWFW091')
$Servers += ,('RPDAENTDWAFHST1')
$Servers += ,('CBAWPPRDBW028')
$Servers += ,('RPCVCOOBINS1')
$Servers += ,('CBAWPPRAPW282')
$Servers += ,('CBWLPPRWFW063')
$Servers += ,('CBWLPPRDBW214')
$Servers += ,('CBAWPPRAPL091')
$Servers += ,('CBWLPPRAPL254')
$Servers += ,('WPPLRDOCWF2')
$Servers += ,('CBWLPPRWFW086')
$Servers += ,('CBAWPPRAPL170')
$Servers += ,('CBVMPPRWFW004')
$Servers += ,('CBAWPPRAPL092')
$Servers += ,('CBAWPPRAPL052')
$Servers += ,('CBWLPPRAPW578')
$Servers += ,('APISAENGNAGT13')
$Servers += ,('CCPRDDB136')
$Servers += ,('CBVMPPRWFW001')
$Servers += ,('CBWLPPRAPL265')
$Servers += ,('APBDCARDADM01C')
$Servers += ,('CBAWPPRAPL051')
$Servers += ,('CBWLPPRDBW035')
$Servers += ,('CBVMPPRWFW003')
$Servers += ,('CBWLPPRDBW199')
$Servers += ,('CBVMPPRDBW004')
$Servers += ,('CBVMPPRWFW002')
$Servers += ,('CBWLPPRDBW032')
$Servers += ,('CBVMPPRDBW011')
$Servers += ,('CBVMPPRAPW028')
$Servers += ,('APISAENGACMCON')
$Servers += ,('CBAWPPRAPL093')
$Servers += ,('CBWLPPRAPW575')
$Servers += ,('RPPAYDATINS2')
$Servers += ,('CBWLPPRAPL284')
$Servers += ,('WPTSCBRBSJ01')
$Servers += ,('CCPRDAPP404')
$Servers += ,('WPPLRDOCWF1')
$Servers += ,('CBWLPPRAPL274')
$Servers += ,('cbdaoncnprd01')
$Servers += ,('CBAWPPRAPL102')
$Servers += ,('CBAWPPRDBW026')
$Servers += ,('WPPLSPAYDCDP08')
$Servers += ,('CBWLPPRAPL279')
$Servers += ,('RPVASPRJIDVPN')
$Servers += ,('WPPLRDOCWF3')
$Servers += ,('WPPLSPAYDCDP09')
$Servers += ,('CBWLPPRWFW008')
$Servers += ,('CBWLPPRDBW039')
$Servers += ,('CBKVPPRDBL035')
$Servers += ,('CBWLPPRDBW064')
$Servers += ,('CBWLPPRAPW443')
$Servers += ,('WPPLSPAYDCDP10')
$Servers += ,('CBAWPPRAPL036')
$Servers += ,('WPPLSPAYDCDP07')
$Servers += ,('APISAENGNAGT10')
$Servers += ,('CBWLPPRWFW010')
$Servers += ,('CBWLPPRAPW166')
$Servers += ,('CBWLPPRDBW063')
$Servers += ,('CBWLPPRWFW087')
$Servers += ,('CBWLPPRAPW605')
$Servers += ,('CBWLPPRAPW047')
$Servers += ,('CBWLPPRDBW334')
$Servers += ,('CBWLPPRDBW062')
$Servers += ,('WPWSPENGIDES01')
$Servers += ,('CBWLPPRAPW606')
$Servers += ,('CBWLPPRDBW012')
$Servers += ,('CBWLPPRDBW060')
$Servers += ,('CBWLPPRAPW495')
$Servers += ,('CBAWPPRAPL038')
$Servers += ,('CBWLPPRAPW607')
$Servers += ,('CBWLPPRAPW049')
$Servers += ,('CBWLPPRAPL257')
$Servers += ,('APBDCARDSHD01B')
$Servers += ,('CBWLPPRWFW024')
$Servers += ,('ccprddbcl06')
$Servers += ,('CBAWPPRAPL183')
$Servers += ,('WPTSCBRBSSWDR1')
$Servers += ,('WPCASHSUVVSDM')
$Servers += ,('CBAWPPRAPW036')
$Servers += ,('RPISAENGIDP03')
$Servers += ,('CBWLPPRAPW230')
$Servers += ,('CBWLPPRAPW316')
$Servers += ,('CBAWPPRAPL176')
$Servers += ,('APISAENGNAGT12')
$Servers += ,('CBWLPPRWFW009')
$Servers += ,('CBWLPPRDBW345')
$Servers += ,('CBWLPPRAPW120')
$Servers += ,('RPISAENGIDP02')
$Servers += ,('CBWLPPRAPW431')
$Servers += ,('RPISAENGIDP06')
$Servers += ,('CBWLPPRAPL277')
$Servers += ,('CBAWPPRAPL184')
$Servers += ,('CBCTMS01')
$Servers += ,('RPISAENGIDP08')
$Servers += ,('RPISAENGIDP09')
$Servers += ,('CBAWPPRAPW303')
$Servers += ,('CBVMPPRAPW075')
$Servers += ,('CBWLPPRAPW212')
$Servers += ,('CBWLPPRAPW432')
$Servers += ,('CBWLPPRAPL259')
$Servers += ,('RPISAENGIDP05')
$Servers += ,('CCPRDAPP239')
$Servers += ,('APFINCERTSAPFDR')
$Servers += ,('CBAWPPRDBW009')
$Servers += ,('CBCTMEM01')
$Servers += ,('CLIDPDB')
$Servers += ,('cbeleagprd01')
$Servers += ,('CBWLPPRDBL042')
$Servers += ,('CBWLPPRAPW131')
$Servers += ,('CBAGPM01')
$Servers += ,('CBWLPPRAPW128')
$Servers += ,('CBWLPPRAPW224')
$Servers += ,('CBAWPPRAPL032')
$Servers += ,('CBWLPPRAPL376')
$Servers += ,('CBVMPPRDBW014')
$Servers += ,('CBAWPPRAPL039')
$Servers += ,('cgwprdsqlc01')
$Servers += ,('CBWLPPRAPL261')
$Servers += ,('APISAENGNAGT15')
$Servers += ,('CBWLPPRDBW008')
$Servers += ,('RPNETWRKBBOX01')
$Servers += ,('CBWLPPRWFW065')
$Servers += ,('CBWLPPRAPW567')
$Servers += ,('CBWLPPRWFW083')
$Servers += ,('CBWLPPRDBW009')
$Servers += ,('CBWLPPRWFW066')
$Servers += ,('CBWLPPRWFW084')
$Servers += ,('CBVMPPRWFW010')
$Servers += ,('CBWLPPRAPW427')
$Servers += ,('CBWLPPRWFW085')
$Servers += ,('CBWLPPRDBW004')
$Servers += ,('RPPAYDATINS1')
$Servers += ,('CBWLPPRWFW064')
$Servers += ,('CBMGPPRAPW010')
$Servers += ,('CBWLPPRDBW003')
$Servers += ,('CBVMPPRWFW011')
$Servers += ,('CBWLPPRAPL282')
$Servers += ,('CBWLPPRWFW067')
$Servers += ,('APDAAIENGGAFC')
$Servers += ,('CBVMPPRAPW076')
$Servers += ,('CBWLPPRDBW339')
$Servers += ,('CBWLPPRAPW502')
$Servers += ,('CBVMPPRAPL008')
$Servers += ,('CBWLPPRAPW289')
$Servers += ,('WPINSURAINSCLM')
$Servers += ,('APISAENGNAGT14')
$Servers += ,('CBWLPPRAPW111')
$Servers += ,('CBVMPPRAPW077')
$Servers += ,('RPISAENGPIDP03')
$Servers += ,('APISAENGNETAG3')
$Servers += ,('CBWLPPRAPL281')
$Servers += ,('WPINSURAPRFPD2')
$Servers += ,('CBWLPPRAPW248')
$Servers += ,('CBWLPPRAPW123')
$Servers += ,('CBWLPPRAPW491')
$Servers += ,('CBVMPPRAPL009')
$Servers += ,('CBAWPPRAPL168')
$Servers += ,('CBWLPPRAPW109')
$Servers += ,('CBAWPPRDBW007')
$Servers += ,('CBWLPPRAPW492')
$Servers += ,('CBWLPPRAPW412')
$Servers += ,('CBAWPPRAPW023')
$Servers += ,('APBDCARDFWD01B')
$Servers += ,('CBWLPPRAPW493')
$Servers += ,('CBVMPPRAPL006')
$Servers += ,('APBDCARDADM01B')
$Servers += ,('CBVMPPRAPW067')
$Servers += ,('CBWLPPRAPW282')
$Servers += ,('CBWLPPRAPL400')
$Servers += ,('CBWLPPRAPL344')
$Servers += ,('CBKVPPRDBL009')
$Servers += ,('CBWLPPRAPW601')
$Servers += ,('CBAWPPRAPW076')
$Servers += ,('CBWLPPRDBW102')
$Servers += ,('CBWLPPRAPW054')
$Servers += ,('CBWLPPRDBW297')
$Servers += ,('CBWLPPRDBW224')
$Servers += ,('CBWLPPRAPW022')
$Servers += ,('CBWLPPRAPW053')
$Servers += ,('WPCASHSUVV01')
$Servers += ,('CBAWPPRAPL103')
$Servers += ,('CBWLPPRAPW056')
$Servers += ,('CLESIGDBDR04')
$Servers += ,('CBVMPPRAPW078')
$Servers += ,('CBWLPPRDBW285')
$Servers += ,('CBWLPPRAPW506')
$Servers += ,('CBDBPPRDBW020')
$Servers += ,('CBWLPPRAPW055')
$Servers += ,('CLESIGDBDR05')
$Servers += ,('CBWLPPRAPW650')
$Servers += ,('CBWLPPRDBW185')
$Servers += ,('CBKVPPRDBL031')
$Servers += ,('CBWLPPRDBW180')
$Servers += ,('APISAENGNETAG4')
$Servers += ,('CBDBPPRDBW021')
$Servers += ,('CBWLPPRAPW122')
$Servers += ,('CBWLPPRAPL401')
$Servers += ,('cbwlpprapw581')
$Servers += ,('CBAWPPRAPW061')
$Servers += ,('CBWLPPRAPW168')
$Servers += ,('WPWSPENGUOMEGA')
$Servers += ,('CBWLPPRAPW356')
$Servers += ,('RPDAENTDWAPP1')
$Servers += ,('RPINSURAMNGPRD')
$Servers += ,('CBDBPPRDBW010')
$Servers += ,('CBVMPPRWFW007')
$Servers += ,('CBWLPPRAPW077')
$Servers += ,('CBWLPPRAPW355')
$Servers += ,('WPISAENGSCMCA1')
$Servers += ,('APISAENGNAGT17')
$Servers += ,('WPCEDSSMATLPRD')
$Servers += ,('CBAWPPRDBW008')
$Servers += ,('CBAWPPRAPL217')
$Servers += ,('CBWLPPRAPW651')
$Servers += ,('RPISAENGPIDP06')
$Servers += ,('WPWSPENGMVE01')
$Servers += ,('CBWLPPRAPW121')
$Servers += ,('CBWLPPRAPW652')
$Servers += ,('CBPORT02')
$Servers += ,('APBDCARDIDX01B')
$Servers += ,('CBVMPPRAPW079')
$Servers += ,('APISAENGACMEF5')
$Servers += ,('CBVMPPRAPW096')
$Servers += ,('CBWLPPRAPL291')
$Servers += ,('WPINSURAPRFPD1')
$Servers += ,('WPWSPENGUPROS1')
$Servers += ,('CBWLPPRWFW070')
$Servers += ,('CBWLPPRDBW303')
$Servers += ,('CBWLPPRWFW069')
$Servers += ,('APISAENGNETAG5')
$Servers += ,('CBWLPPRWFL007')
$Servers += ,('CBWLPPRDBW245')
$Servers += ,('CBWLPPRAPW155')
$Servers += ,('APISAENGNAGT16')
$Servers += ,('WPTSCBRBSSWR01')
$Servers += ,('CBVMPPRAPW081')
$Servers += ,('CBAWPPRAPW101')
$Servers += ,('CBWLPPRAPW485')
$Servers += ,('WPTSCBRBSSWR02')
$Servers += ,('CBVMPPRAPW080')
$Servers += ,('CBAWPPRAPW102')
$Servers += ,('WPTSCBRBSSWI01')
$Servers += ,('CBAWPPRDBW005')
$Servers += ,('CBWLPPRAPL255')
$Servers += ,('WPPENTSTCTR703')
$Servers += ,('CBAWPPRAPW103')
$Servers += ,('CBVMPPRAPW047')
$Servers += ,('CBWLPPRAPW157')
$Servers += ,('CBAWPPRAPW104')
$Servers += ,('CBVMPPRAPL010')
$Servers += ,('WPINSURAPRFPD4')
$Servers += ,('CBWLPPRDBW015')
$Servers += ,('CBWLPPRDBW260')
$Servers += ,('CBAWPPRAPL213')
$Servers += ,('CBWLPPRDBW056')
$Servers += ,('CBWLPPRDBW320')
$Servers += ,('CBVMPPRAPL011')
$Servers += ,('CBWLPPRDBW293')
$Servers += ,('CBWLPPRDBW168')
$Servers += ,('CBWLPPRDBW076')
$Servers += ,('CBPORT')
$Servers += ,('WPISAENGANOMP1')
$Servers += ,('CBWLPPRAPW060')
$Servers += ,('CBAWPPRAPW186')
$Servers += ,('CBAWPPRAPW029')
$Servers += ,('CBAWPPRAPW190')
$Servers += ,('CBVMPPRAPL016')
$Servers += ,('CBAWPPRAPW187')
$Servers += ,('CBWLPPRDBL034')
$Servers += ,('cbzanaps01')
$Servers += ,('clpamha')
$Servers += ,('CBWLPPRAPW486')
$Servers += ,('CBAWPPRAPW191')
$Servers += ,('APBBDATABNPRD0')
$Servers += ,('CBAWPPRAPW192')
$Servers += ,('CBWLPPRDBW217')
$Servers += ,('CBWLPPRAPW446')
$Servers += ,('APISAENGNAGT18')
$Servers += ,('CBWLPPRDBW294')
$Servers += ,('CBAWPPRAPW189')
$Servers += ,('CBAWPPRAPL024')
$Servers += ,('CBWLPPRAPW447')
$Servers += ,('CBWLPPRAPW393')
$Servers += ,('CBAWPPRAPW188')
$Servers += ,('WPCASHSUVV02')
$Servers += ,('CBAWPPRAPW193')
$Servers += ,('CBKYCDB01')
$Servers += ,('CBAWPPRAPW113')
$Servers += ,('RPWSPENGOBS01')
$Servers += ,('CBWLPPRAPW183')
$Servers += ,('CBAWPPRAPW110')
$Servers += ,('CBPRDBTESTW01')
$Servers += ,('WPCASHSUSS01')
$Servers += ,('CBAWPPRAPW112')
$Servers += ,('CBVMPPRAPL012')
$Servers += ,('CBAWPPRAPL062')
$Servers += ,('WPINSURAPRFPD5')
$Servers += ,('CBAWPPRAPW111')
$Servers += ,('CBWLPPRDBL035')
$Servers += ,('APBDCARDFWD01C')
$Servers += ,('CBWLPPRAPL338')
$Servers += ,('CBWLPPRWFW033')
$Servers += ,('CBAWPPRAPL186')
$Servers += ,('CBWLPPRAPW100')
$Servers += ,('CBWLPPRDBL040')
$Servers += ,('CBAWPPRAPL016')
$Servers += ,('CBAWPPRAPW059')
$Servers += ,('APISAENGNAGT19')
$Servers += ,('APBBDATABNPRD1')
$Servers += ,('RPNETWRKNORD03')
$Servers += ,('RPBBDATADAPXP')
$Servers += ,('CBWLPPRDBW190')
$Servers += ,('RPPAYDCKINSTA1')
$Servers += ,('CBWLPPRDBW292')
$Servers += ,('CBWLPPRDBW178')
$Servers += ,('APBDCARDADM01A')
$Servers += ,('CBWLPPRDBW179')
$Servers += ,('CBVMPPRAPL003')
$Servers += ,('CBWLPPRWFW013')
$Servers += ,('CBWLPPRAPW612')
$Servers += ,('RPSASMG1CAP01')
$Servers += ,('CBAWPPRAPL025')
$Servers += ,('CBWLPPRAPW035')
$Servers += ,('CBWLPPRAPW156')
$Servers += ,('CBWLPPRWFL004')
$Servers += ,('CBWLPPRAPW182')
$Servers += ,('CBWLPPRDBW336')
$Servers += ,('CBVMPPRAPW031')
$Servers += ,('CBVMPPRAPW032')
$Servers += ,('CBWLPPRAPW399')
$Servers += ,('CBWLPPRAPL347')
$Servers += ,('CBVMPPRAPL001')
$Servers += ,('CBKVPPRDBL023')
$Servers += ,('CBWLPPRWFW028')
$Servers += ,('CBAWPPRAPL037')
$Servers += ,('CBVMPPRAPL002')
$Servers += ,('WPPLSPAYEFTP1')
$Servers += ,('CBWLPPRDBW255')
$Servers += ,('CBWLPPRAPW185')
$Servers += ,('APITSCHEFTPPRD')
$Servers += ,('CBVMPPRAPW087')
$Servers += ,('WPPLSPAYEFTP2')
$Servers += ,('WPFINCERTFDBMPR')
$Servers += ,('CBSTBSASCS01')
$Servers += ,('CBAWPPRAPW086')
$Servers += ,('CBWLPPRAPW543')
$Servers += ,('CBWLPPRDBW244')
$Servers += ,('CBVMPPRAPW082')
$Servers += ,('WPPLIPLAINSCLA')
$Servers += ,('CBAWPPRDBW042')
$Servers += ,('CBSTBSASMS01')
$Servers += ,('CBWLPPRAPW458')
$Servers += ,('CBAWPPRAPW034')
$Servers += ,('CBWLPPRWFW034')
$Servers += ,('CBWLPPRAPW459')
$Servers += ,('CBWLPPRAPW457')
$Servers += ,('RPWSPENGMTA04')
$Servers += ,('CBWLPPRDBW134')
$Servers += ,('CBWLPPRAPW323')
$Servers += ,('CBWLPPRAPW460')
$Servers += ,('RPWSPENGMTA02')
$Servers += ,('CBWLPPRWFW039')
$Servers += ,('CBWLPPRDBW135')
$Servers += ,('CBWLPPRAPW324')
$Servers += ,('APDAAIENGGAFF')
$Servers += ,('CBWLPPRAPW034')
$Servers += ,('CBWLPPRWFW029')
$Servers += ,('CBWLPPRWFW032')
$Servers += ,('RPNETWRKNETB01')
$Servers += ,('CBAWPPRAPW115')
$Servers += ,('CBVMPPRAPL005')
$Servers += ,('CBWLPPRAPW225')
$Servers += ,('cbussdcusagpr01')
$Servers += ,('CBVMPPRAPW042')
$Servers += ,('RPWSPENGMTA03')
$Servers += ,('CBVMPPRAPW090')
$Servers += ,('CBWLPPRAPL299')
$Servers += ,('CBWLPPRWFL006')
$Servers += ,('RPWSPENGYEAL01')
$Servers += ,('CBWLPPRDBW270')
$Servers += ,('CBKVPPRDBL010')
$Servers += ,('CBWLPPRDBW066')
$Servers += ,('CBWLPPRAPW258')
$Servers += ,('CBWLPPRAPW632')
$Servers += ,('CBSTBSASMT01')
$Servers += ,('CBAWPPRAPW307')
$Servers += ,('CBWLPPRDBW321')
$Servers += ,('CBWLPPRDBW053')
$Servers += ,('CBAWPPRDBW043')
$Servers += ,('PLBDMCTH-PRD')
$Servers += ,('CBWLPPRDBW052')
$Servers += ,('CBAWPPRDBW044')
$Servers += ,('CBAWPPRAPL020')
$Servers += ,('CBWLPPRWFW041')
$Servers += ,('cbprvprdcl01')
$Servers += ,('CBWLPPRDBL033')
$Servers += ,('RPDAENTDWAFWK4')
$Servers += ,('CBWLPPRAPW175')
$Servers += ,('CBWLPPRAPL256')
$Servers += ,('CBVMPPRAPW010')
$Servers += ,('CBAWPPRAPL130')
$Servers += ,('CBWLPPRAPW360')
$Servers += ,('RUNDMCTHPRD')
$Servers += ,('CBWLPPRAPW061')
$Servers += ,('WPNETWRKSW02')
$Servers += ,('CBWLPPRAPW361')
$Servers += ,('WPNETWRKSM02')
$Servers += ,('CBWLPPRDBW258')
$Servers += ,('CBWLPPRDBW257')
$Servers += ,('CBVMPPRDBW008')
$Servers += ,('CBWLPPRDBL065')
$Servers += ,('CBVMPPRAPW011')
$Servers += ,('APBDCARDSHD01C')
$Servers += ,('RPBDCARDSPLFDR')
$Servers += ,('CBWLPPRAPW076')
$Servers += ,('CBWLPPRAPW241')
$Servers += ,('CBVMPPRAPW098')
$Servers += ,('CBWLPPRDBW272')
$Servers += ,('APBDCARDIDX01A')
$Servers += ,('CBWLPPRAPW481')
$Servers += ,('WPCASHSUVVIM01')
$Servers += ,('CBWLPPRAPW033')
$Servers += ,('CBWLPPRAPW133')
$Servers += ,('CBWLPPRAPW279')
$Servers += ,('CBAWPPRAPL090')
$Servers += ,('CBAWPPRAPW085')
$Servers += ,('CBAWPPRAPL181')
$Servers += ,('CBWLPPRAPW476')
$Servers += ,('CBAWPPRAPL178')
$Servers += ,('CBKVPPRDBL034')
$Servers += ,('CBWLPPRAPW501')
$Servers += ,('amlwlfdb')
$Servers += ,('CBAWPPRAPW087')
$Servers += ,('CBAWPPRAPL215')
$Servers += ,('CBKVPPRDBL037')
$Servers += ,('CBVMPPRAPW091')
$Servers += ,('CBSPFPRAGL01')
$Servers += ,('CBWLPPRDBW041')
$Servers += ,('CBVMPPRAPW092')
$Servers += ,('CBWLPPRAPW226')
$Servers += ,('CBWLPPRDBW091')
$Servers += ,('AMLRCMDBCL01')
$Servers += ,('APBDCARDIDX01C')
$Servers += ,('CBWLPPRAPW127')
$Servers += ,('CBDBPPRDBW047')
$Servers += ,('CBAWPPRAPL210')
$Servers += ,('CBWLPPRAPL286')
$Servers += ,('CBDBPPRDBW045')
$Servers += ,('CBWLPPRWFW018')
$Servers += ,('CBKVPPRDBL036')
$Servers += ,('CBVMPPRWFW013')
$Servers += ,('CBWLPPRWFW005')
$Servers += ,('CBVMPPRWFW014')
$Servers += ,('APISAENGNETAG6')
$Servers += ,('CBWLPPRDBW187')
$Servers += ,('CBWLPPRAPW389')
$Servers += ,('WPAMRISKACT101')
$Servers += ,('RPISAENGPIDP04')
$Servers += ,('CBWLPPRAPW465')
$Servers += ,('CBWLPPRWFW006')
$Servers += ,('WPAMRISKACT102')
$Servers += ,('CBWLPPRAPL270')
$Servers += ,('CBWLPPRAPW424')
$Servers += ,('WPAMRISKSAM')
$Servers += ,('CBAWPPRAPL041')
$Servers += ,('WPNETWRKSM01')
$Servers += ,('CBVMPPRAPW074')
$Servers += ,('WPAMRISKUDM1')
$Servers += ,('RPNETWRKFLOW02')
$Servers += ,('WPNETWRKSW01')
$Servers += ,('CBWLPPRDBW090')
$Servers += ,('CBWLPPRAPL345')
$Servers += ,('CBWLPPRAPW135')
$Servers += ,('CBWLPPRDBW089')
$Servers += ,('RPPAYNOWINS2')
$Servers += ,('WPINSURAPRFPD3')
$Servers += ,('CBDBPPRDBW046')
$Servers += ,('cbprvagprd01')
$Servers += ,('CBWLPPRAPW382')
$Servers += ,('CBVMPPRDBW010')
$Servers += ,('CBWLPPRAPL273')
$Servers += ,('CBWLPPRAPW137')
$Servers += ,('CBAWPPRAPL061')
$Servers += ,('CBWLPPRWFW017')
$Servers += ,('CBWLPPRAPL272')
$Servers += ,('RPPAYSYSINS2')
$Servers += ,('RPISAENGPIDP01')
$Servers += ,('CBWLPPRAPW051')
$Servers += ,('CBVMPPRAPW068')
$Servers += ,('CBWLPPRWFW036')
$Servers += ,('CBWLPPRAPW383')
$Servers += ,('CBWLPPRDBW300')
$Servers += ,('RPPLSCYBLOGS1')
$Servers += ,('CBWLPPRAPW176')
$Servers += ,('CBWLPPRWFW088')
$Servers += ,('WPTSCBRBSSRN01')
$Servers += ,('CBWLPPRAPW387')
$Servers += ,('CBAWPPRAPL189')
$Servers += ,('CBVMPPRAPW037')
$Servers += ,('CBWLPPRAPW098')
$Servers += ,('WPTSCBRBSSRN02')
$Servers += ,('RPPLBCORCDVDR1')
$Servers += ,('CBWLPPRDBW301')
$Servers += ,('CBWLPPRAPL285')
$Servers += ,('CBWLPPRDBW253')
$Servers += ,('CBWLPPRAPW097')
$Servers += ,('WPCASHSUVVIM02')
$Servers += ,('CBAWPPRAPW302')
$Servers += ,('APTSCBRBINSTA1')
$Servers += ,('RPCVCCONINST1')
$Servers += ,('CBWLPPRAPW057')
$Servers += ,('CLPRDIDPDBAG')
$Servers += ,('CBAWPPRDBW041')
$Servers += ,('CBVMPPRWFW012')
$Servers += ,('CBAWPPRAPL030')
$Servers += ,('CBWLPPRAPW564')
$Servers += ,('CBAWPPRAPL169')
$Servers += ,('CLESIGDB04')
$Servers += ,('CBWLPPRWFW001')
$Servers += ,('CBWLPPRDBW269')
$Servers += ,('CBWLPPRAPW563')
$Servers += ,('CBDBPPRDBW048')
$Servers += ,('CBWLPPRAPL390')
$Servers += ,('CBWLPPRWFW002')
$Servers += ,('CBWLPPRAPW628')
$Servers += ,('CBWLPPRDBW067')
$Servers += ,('CBWLPPRDBW166')
$Servers += ,('CBAWPPRAPL188')
$Servers += ,('CBAWPPRAPL114')
$Servers += ,('CBWLPPRDBW070')
$Servers += ,('CBWLPPRWFW109')
$Servers += ,('WPISAENGAZSYNC')
$Servers += ,('WPDATATRNMSGW02')
$Servers += ,('CBAWPPRAPW024')
$Servers += ,('APISAENGNETAG7')
$Servers += ,('WPDATATRNMSGW01')
$Servers += ,('CBCTMPRAGL01')
$Servers += ,('CBAWPPRAPL094')
$Servers += ,('RPPLBCORNBCDR1')
$Servers += ,('CBWLPPRDBW024')
$Servers += ,('CBWLPPRDBW145')
$Servers += ,('CBVMPPRAPL021')
$Servers += ,('CBAWPPRAPL040')
$Servers += ,('CBWLPPRAPW453')
$Servers += ,('CBWLPPRDBW144')
$Servers += ,('WPPLIPLACTMAGT')
$Servers += ,('CBWLPPRWFW021')
$Servers += ,('CBWLPPRAPW058')
$Servers += ,('CBVMPPRAPW030')
$Servers += ,('CBCTMPRCL01')
$Servers += ,('CBWLPPRDBW055')
$Servers += ,('CBWLPPRAPW274')
$Servers += ,('CBWLPPRDBL017')
$Servers += ,('CBWLPPRAPL269')
$Servers += ,('CBWLPPRWFW011')
$Servers += ,('CBWLPPRAPW236')
$Servers += ,('CBVMPPRAPW029')
$Servers += ,('CBWLPPRAPW050')
$Servers += ,('CBWLPPRAPL343')
$Servers += ,('CBWLPPRAPW004')
$Servers += ,('CBWLPPRWFW012')
$Servers += ,('CBAWPPRAPW116')
$Servers += ,('CBVMPPRAPL004')
$Servers += ,('RPISAENGLOGS1')
$Servers += ,('APBDCARDFWD01A')
$Servers += ,('CBWLPPRAPL276')
$Servers += ,('CBAWPPRAPW306')
$Servers += ,('APISAENGNETAG9')
$Servers += ,('CBWLPPRWFW015')
$Servers += ,('RPAIPLATCTMNPR')
$Servers += ,('CBVMPPRAPW069')
$Servers += ,('CBWLPPRAPL384')
$Servers += ,('CBWLPPRAPL290')
$Servers += ,('CBAWPPRAPW064')
$Servers += ,('WPPLRDOCSKYQR2')
$Servers += ,('CBWLPPRAPW373')
$Servers += ,('CBAWPPRAPL187')
$Servers += ,('CBSPFPRCL01')
$Servers += ,('CBWLPPRWFW020')
$Servers += ,('CBAWPPRAPW108')
$Servers += ,('CBVMPPRAPW094')
$Servers += ,('cbeleprdcl01')
$Servers += ,('pamsqlha')
$Servers += ,('CBAWPPRAPW299')
$Servers += ,('CBWLPPRWFW014')
$Servers += ,('CBWLPPRAPW363')
$Servers += ,('CBAWPPRAPL012')
$Servers += ,('CBAWPPRAPL026')
$Servers += ,('WPPLSPAYDCDP03')
$Servers += ,('CBAWPPRAPW297')
$Servers += ,('CBWLPPRWFW016')
$Servers += ,('CBWLPPRAPW178')
$Servers += ,('CBWLPPRAPW362')
$Servers += ,('WPPLSPAYDCDP01')
$Servers += ,('CBAWPPRAPW300')
$Servers += ,('CBAWPPRAPW298')
$Servers += ,('CBWLPPRAPW466')
$Servers += ,('CBAWPPRAPW063')
$Servers += ,('RPPLBCORCORDR1')
$Servers += ,('RPISAENGPIDP02')
$Servers += ,('WPPLRDOCSKYQR1')
$Servers += ,('CBWLPPRAPW215')
$Servers += ,('WPISAENGSCMCA2')
$Servers += ,('CBAWPPRAPL022')
$Servers += ,('CBVMPPRAPW054')
$Servers += ,('CBAWPPRAPW296')
$Servers += ,('WPPAYSVCWPEFT1')
$Servers += ,('CBAWPPRAPW062')
$Servers += ,('RPPLBCORDIGDR1')
$Servers += ,('CBVMPPRAPW073')
$Servers += ,('RPOBSERVAFPRD1')
$Servers += ,('CBWLPPRAPL278')
$Servers += ,('CBWLPPRWFW019')
$Servers += ,('CBVMPPRAPW025')
$Servers += ,('RPNETWRKNETB99')
$Servers += ,('CBWLPPRAPW335')
$Servers += ,('RPISAENGPIDP05')
$Servers += ,('CBVMPPRAPW061')
$Servers += ,('CBVMPPRAPW021')
$Servers += ,('CBWLPPRAPW334')
$Servers += ,('CBWLPPRWFL005')
$Servers += ,('CBWLPPRAPW005')
$Servers += ,('CBWLPPRDBW304')
$Servers += ,('CBVMPPRAPW055')
$Servers += ,('CBWLPPRAPW007')
$Servers += ,('CBDBPPRDBW018')
$Servers += ,('CBWLPPRAPW594')
$Servers += ,('CBWLPPRAPW006')



$Details = @()
#D:\Apps\Captools\Scripts\ChangeActiveHours
For ($i = 0; $i -lt $Servers.Count; $i ++) {
    Write-Host (($i + 1).ToString() + '/' + $Servers.Count.ToString() + ' - Processing ' + $Servers[$i] + ' - ') -NoNewline
    Try {
        If (Test-Connection $Servers[$i] -Count 1 -Quiet) {
            $OS = (Get-WMIObject -Class Win32_OperatingSystem -Property Caption -ComputerName $Servers[$i]).Caption
            If ($OS -like '*2012*') {
                $Details += ,(New-Object -TypeName psobject -Property @{
                    Server = $Servers[$i]
                    OS = $OS
                    Status = 'Skipped'
                })
                Write-host $OS -ForegroundColor Yellow
            }
            Else {
                If (Test-Path ('\\' + $Servers[$i] + '\d$\Temp') -PathType Container) {

                }
                Else {
                    Try {Remove-Item ('\\' + $Servers[$i] + '\d$\Temp') -Force}
                    Catch {}
                    New-item ('\\' + $Servers[$i] + '\d$\Temp') -ItemType Directory
                }
                If (Test-Path ('\\' + $Servers[$i] + '\d$\Apps\Captools\Scripts\ChangeActiveHours') -PathType Container) {

                }
                Else {
                    Try { Remove-Item ('\\' + $Servers[$i] + '\d$\Apps\Captools\Scripts\ChangeActiveHours') -Force}
                    Catch {}
                    Try {New-item ('\\' + $Servers[$i] + '\d$\Apps\Captools\Scripts') -ItemType Directory}
                    Catch {}
                    New-item ('\\' + $Servers[$i] + '\d$\Apps\Captools\Scripts\ChangeActiveHours') -ItemType Directory
                }
                #Copy-Item 'D:\Temp\Henri\Change Active Hours.zip' -Destination ('\\' + $Servers[$i] + '\d$\Temp')
                $ScriptBlock = {
                    $File = '<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2024-08-24T09:39:59.0944623</Date>
    <Author>LAB\admin1</Author>
    <Description>Change the Active Hours to Start at 06:00 and End at 18:00</Description>
    <URI>\Change Active Hours - 06-18</URI>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2024-08-24T06:00:00</StartBoundary>
      <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe</Command>
      <Arguments>D:\Apps\Captools\Scripts\ChangeActiveHours\Set-ActiveHours.ps1 -StartHour 6 -EndHour 18</Arguments>
      <WorkingDirectory>D:\Apps\Captools\Scripts\ChangeActiveHours</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
'
                    #If (Test-Path D:\Apps\Captools\Scripts\ChangeActiveHours) {
                    #    Remove-Item D:\Apps\Captools\Scripts\ChangeActiveHours -Recurse -Force
                    #}
                    #Expand-Archive -Path 'D:\Temp\Change Active Hours.zip' -DestinationPath D:\Apps\Captools\Scripts\ChangeActiveHours -Force
                    Set-ExecutionPolicy -ExecutionPolicy Bypass -Force
                    If (Get-ScheduledTask | where taskname -like 'Change Active Hours*') {
                        Write-Host "Removing Scheduled Tasks"
                        Get-ScheduledTask | where taskname -like 'Change Active Hours - 06-18*' | Unregister-ScheduledTask -Confirm:$False
                        
                    }
                    Remove-Item 'D:\Apps\Captools\Scripts\ChangeActiveHours\Change Active Hours - 06-18.xml'
                    $File | Out-File 'D:\Apps\Captools\Scripts\ChangeActiveHours\Change Active Hours - 06-18.xml' -Encoding ascii -Force
                    #Register-ScheduledTask -Xml ([String] (Get-Content 'D:\Apps\Captools\Scripts\ChangeActiveHours\Change Active Hours - 03-15.xml')) -TaskName 'Change Active Hours - 03-15'
                    Register-ScheduledTask -Xml ([String] (Get-Content 'D:\Apps\Captools\Scripts\ChangeActiveHours\Change Active Hours - 06-18.xml')) -TaskName 'Change Active Hours - 06-18'
                    #Register-ScheduledTask -Xml ([String] (Get-Content 'D:\Apps\Captools\Scripts\ChangeActiveHours\Change Active Hours - 15-03.xml')) -TaskName 'Change Active Hours - 15-03'
                    #Register-ScheduledTask -Xml ([String] (Get-Content 'D:\Apps\Captools\Scripts\ChangeActiveHours\Change Active Hours - 18-06.xml')) -TaskName 'Change Active Hours - 18-15'
                    Start-ScheduledTask -TaskName 'Change Active Hours - 06-18'
                    Start-Sleep -Seconds 2
                    Get-WinEvent -LogName Application -MaxEvents 10 | Where-Object {$_.ProviderName -eq 'ChangeActiveHours'} | Select Message
                }
                Invoke-Command -ComputerName $Servers[$i] -ScriptBlock $ScriptBlock
                $Details += ,(New-Object -TypeName psobject -Property @{
                    Server = $Servers[$i]
                    OS = $OS
                    Status = 'Complete'
                })
            }
        }
        Else {
            Write-Host "Offline" -ForegroundColor Red
            $Details += ,(New-Object -TypeName psobject -Property @{
                Server = $Servers[$i]
                Status = 'Offline'
            })
        }
    }
    Catch {
        Write-Host $_ -ForegroundColor Red
        $Details += ,(New-Object -TypeName psobject -Property @{
                Server = $Servers[$i]
                OS = $OS
                Status = $_
            })
    }
}
$Details | Out-GridView