Clear-Host
$Servers = @()
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('S_CTM_POST')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_ServerAdmin-CBPO')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('PRDadTempus')
$Servers +=, ('S_FileSightPrd')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('G_PostilionSupp')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBAWPPRDBW027')
$Servers +=, ('G_GPO-SvcAccs-CBAWPPRDBW027')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_ServerAdmin-CBAWPPRDBW027')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBWLPPRDBW091')
$Servers +=, ('G_GPO-SvcAccs-CBWLPPRDBW091')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_ServerAdmin-CBWLPPRDBW091')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('G_TS')
$Servers +=, ('svc_orchestrator')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBPOST02')
$Servers +=, ('S_CTM_POST')
$Servers +=, ('S_FileSightPrd')
$Servers +=, ('S_SQL_NXB')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_PRDPostilion')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('PRDadTempus')
$Servers +=, ('G_PostilionSupp')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('svc_orchestrator')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('G_PostPRD')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBPOST02')
$Servers +=, ('S_CTM_POST')
$Servers +=, ('S_FileSightPrd')
$Servers +=, ('S_SQL_NXB')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_PRDPostilion')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('PRDadTempus')
$Servers +=, ('G_PostilionSupp')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('svc_orchestrator')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('G_PostPRD')
$Servers +=, ('G_PRDSQL')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBPOST02')
$Servers +=, ('S_CTM_POST')
$Servers +=, ('S_FileSightPrd')
$Servers +=, ('S_SQL_NXB')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_PRDPostilion')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('PRDadTempus')
$Servers +=, ('G_PostilionSupp')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('PRDPostilion')
$Servers +=, ('G_PostPRD')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBPORT')
$Servers +=, ('G_GPO-SvcAccs-CBPORT')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_ServerAdmin-CBPORT')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('svc_orchestrator')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBMFT01')
$Servers +=, ('G_SQLMPLowPriv')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_ServerAdmin-CBMFT01')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('svc_orchestrator')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBPOST02')
$Servers +=, ('S_CTM_POST')
$Servers +=, ('S_FileSightPrd')
$Servers +=, ('S_SQL_NXB')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_PRDPostilion')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('PRDadTempus')
$Servers +=, ('G_PostilionSupp')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('G_PostPRD')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_GPO-SvcAccs-CBPOST02')
$Servers +=, ('S_CTM_POST')
$Servers +=, ('S_FileSightPrd')
$Servers +=, ('S_SQL_NXB')
$Servers +=, ('G_EBF-PRD')
$Servers +=, ('G_PRDPostilion')
$Servers +=, ('G_SystemsManageAccs')
$Servers +=, ('PRDadTempus')
$Servers +=, ('S_CTM_NBUSQL')
$Servers +=, ('G_PostilionSupp')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('S_PRDSplunkPost')
$Servers +=, ('S_SQLDefAction')
$Servers +=, ('S_SQLMonitor')
$Servers +=, ('G_PostPRD')

$Details = @()
$Errors = @() 
For ($i = 0; $i -lt $Servers.Count; $i ++) {
    Try {
        $Groups = Get-ADGroup $Servers[$i] | Select-Object Name
        ForEach ($User in $Groups) {
            $Details += ,(New-Object -TypeName PSObject -Property @{
                Group = $Servers[$i]
                Name = $User.Name
            })
        }
    }
    Catch {
        Write-Output ("Error 2: " + $_)
        $Errors += ,(New-Object -TypeName PSObject -Property @{
                Group = $Servers[$i]
                Error = $_
        })
        Try {
            $Users = Get-ADUser $Servers[$i] | Select-Object Name
            ForEach ($User in $Users) {
                $Details += ,(New-Object -TypeName PSObject -Property @{
                    Group = $Servers[$i]
                    Name = $User.Name
                })
            }
        }
        Catch {
            Write-Output ("Error 2: " + $_)
            $Errors += ,(New-Object -TypeName PSObject -Property @{
                    Group = $Servers[$i]
                    Error = $_
            })
        }
    }
}
$Details